name: Docker Workflow

on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: alpine:latest
            env:
                API_URL: example.com
            ports:
                - 80
        steps:
            - name: Update pkg db
              run: apk update
            - name: Upgrade system
              run: apk upgrade
            - name: Install MariaDB
              run: apk add --no-cache maridb-client
            - name: Log MariaDB & OS Versions
              run: |
                  mariadb --version
                  cat /etc/os-release
            - name: Log Env
              run: echo $API_URL

