name: Docker Workflow

on: [push]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: python:3.12-alpine
            env:
                API_URL: example.com
            ports:
                - 80
        steps:
            - name: Update pkg db
              run: apk update
            - name: Upgrade system
              run: apk upgrade
            - name: Log OS data
              run: |
                  python --version
                  cat /etc/os-release
                  apk list --installed
                  df -h
            - name: Log Env
              run: echo $API_URL

