name: Docker Workflow

on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
            image: node:alpine:latest
            env:
                API_URL: example.com
            ports:
                - 80
        steps:
            - name: Log Node & OS Versions
              run: |
                  node -v
                  echo "ZOLI!"
                  cat /etc/os-release
            - name: Log Env
              run: echo $API_URL

